/**
 * Identifies queued photos once the device is back online: one at a time, oldest first,
 * with exponential backoff for failures. Runs while the app is open — on start, when the
 * connection returns and when the app comes back to the foreground (see OfflineQueueRunner).
 *
 * Background Sync isn't used: the service worker is generated by Workbox (generateSW) and
 * identification needs the app's own upload code, so a queued photo waits for the next time
 * FieldLens is open with signal.
 */
import type { IdentifyResponse } from '../../../shared/types';
import { ClientError, type ClientErrorCode, type IdentifyRequest } from '../../lib/api';
import {
  getQueued,
  isTakenBySession,
  listQueued,
  removeQueued,
  toRequest,
  updateQueued,
  type QueuedIdentification,
} from './queueStore';

export type QueueDeps = {
  identify: (req: IdentifyRequest) => Promise<IdentifyResponse>;
  /** Saves to the Field Journal; resolves false if it couldn't be saved. */
  save: (item: QueuedIdentification, result: IdentifyResponse) => Promise<boolean>;
  /** Told about each photo that was identified and saved. */
  onIdentified?: (item: QueuedIdentification, result: IdentifyResponse) => void;
  isOnline?: () => boolean;
  now?: () => number;
};

export type QueueRunSummary = {
  identified: number;
  failed: number;
  /** Stopped early because the connection dropped again. */
  offline: boolean;
};

const BASE_DELAY_MS = 30_000;
const MAX_DELAY_MS = 30 * 60_000;
/** Attempts before a (non-connection) error needs the user. */
export const MAX_ATTEMPTS = 6;

/** Errors that won't change by trying again: the item needs the user. */
const PERMANENT: ReadonlySet<ClientErrorCode> = new Set<ClientErrorCode>([
  'invalid_file',
  'image_too_large',
  'too_many_images',
  'unsupported_category',
  'invalid_request',
  'not_configured',
  'provider_auth',
  'zero_predictions',
]);

/** Connection problems: stop this run and try again later. */
const CONNECTION: ReadonlySet<ClientErrorCode> = new Set<ClientErrorCode>(['offline', 'network']);

export function backoffDelay(attempts: number, retryAfterSeconds?: number): number {
  const exp = Math.min(BASE_DELAY_MS * 2 ** Math.max(0, attempts - 1), MAX_DELAY_MS);
  return Math.max(exp, (retryAfterSeconds ?? 0) * 1000);
}

function asClientError(error: unknown): ClientError {
  return error instanceof ClientError
    ? error
    : new ClientError('internal_error', 'Something went wrong.');
}

let running: Promise<QueueRunSummary> | undefined;

/**
 * Processes every waiting item that is due. Concurrent calls share one run.
 * `force` ignores the backoff (the user tapped "Try now").
 */
export function processQueue(
  deps: QueueDeps,
  options: { force?: boolean } = {},
): Promise<QueueRunSummary> {
  running ??= run(deps, options).finally(() => {
    running = undefined;
  });
  return running;
}

async function run(deps: QueueDeps, { force = false }): Promise<QueueRunSummary> {
  const isOnline = deps.isOnline ?? (() => navigator.onLine !== false);
  const now = deps.now ?? Date.now;
  const summary: QueueRunSummary = { identified: 0, failed: 0, offline: false };
  if (!isOnline()) return { ...summary, offline: true };

  const due = (await listQueued()).filter(
    (i) => i.status === 'waiting' && (force || !i.nextAttemptAt || i.nextAttemptAt <= now()),
  );
  for (const { id } of due) {
    if (!isOnline()) return { ...summary, offline: true };
    // Re-read: it may have been removed, or retried by hand, since the list was taken.
    const item = await getQueued(id);
    if (!item || item.status !== 'waiting' || isTakenBySession(id)) continue;

    let result: IdentifyResponse;
    try {
      result = await deps.identify(toRequest(item));
    } catch (e) {
      const error = asClientError(e);
      if (error.code === 'offline' || (!isOnline() && CONNECTION.has(error.code))) {
        // Lost signal again: not the photo's fault, so it doesn't count as an attempt.
        return { ...summary, offline: true };
      }
      const attempts = item.attempts + 1;
      if (PERMANENT.has(error.code) || attempts >= MAX_ATTEMPTS) {
        await updateQueued(id, { status: 'failed', attempts, error: error.message });
        summary.failed++;
        continue;
      }
      await updateQueued(id, {
        attempts,
        nextAttemptAt: now() + backoffDelay(attempts, error.retryAfterSeconds),
        error: error.message,
      });
      // A weak or captive connection, or a busy service: leave the rest for later too.
      if (CONNECTION.has(error.code) || error.code === 'rate_limited') {
        return { ...summary, offline: CONNECTION.has(error.code) };
      }
      continue;
    }

    if (isTakenBySession(id)) continue; // the user's own retry already has it
    if (result.candidates.length === 0) {
      await updateQueued(id, {
        status: 'failed',
        attempts: item.attempts + 1,
        error: 'No match was found. Try a clearer or closer photo.',
      });
      summary.failed++;
      continue;
    }
    // Only drop the queued photo once its Field Journal entry exists.
    if (!(await deps.save(item, result).catch(() => false))) {
      await updateQueued(id, {
        attempts: item.attempts + 1,
        nextAttemptAt: now() + backoffDelay(item.attempts + 1),
        error: 'The result couldn’t be saved on this device.',
      });
      continue;
    }
    await removeQueued(id);
    summary.identified++;
    deps.onIdentified?.(item, result);
  }
  return summary;
}

/** When the next backed-off item becomes due, if any. */
export function nextDueAt(items: QueuedIdentification[]): number | undefined {
  const times = items
    .filter((i) => i.status === 'waiting' && i.nextAttemptAt)
    .map((i) => i.nextAttemptAt!);
  return times.length ? Math.min(...times) : undefined;
}
